// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASWcNQ94U35W1ANOlrT5u73qXO2mVryKE',
    appId: '1:1016815602526:web:98d59175165dd598c51dcf',
    messagingSenderId: '1016815602526',
    projectId: 'whatsappclone-e2322',
    authDomain: 'whatsappclone-e2322.firebaseapp.com',
    storageBucket: 'whatsappclone-e2322.appspot.com',
    measurementId: 'G-Q3D5WJVE9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkpPseGvLfJh43Qd_xYeCuYs8YNX-q8A',
    appId: '1:1016815602526:android:642cdc94254ff1f2c51dcf',
    messagingSenderId: '1016815602526',
    projectId: 'whatsappclone-e2322',
    storageBucket: 'whatsappclone-e2322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-V7ocsqlTOC4_aJzJFNQqK1JUoAtqAU',
    appId: '1:1016815602526:ios:9e927c35cae81413c51dcf',
    messagingSenderId: '1016815602526',
    projectId: 'whatsappclone-e2322',
    storageBucket: 'whatsappclone-e2322.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU-V7ocsqlTOC4_aJzJFNQqK1JUoAtqAU',
    appId: '1:1016815602526:ios:42c9c0f3cd127108c51dcf',
    messagingSenderId: '1016815602526',
    projectId: 'whatsappclone-e2322',
    storageBucket: 'whatsappclone-e2322.appspot.com',
    iosBundleId: 'com.example.whatsappclone.RunnerTests',
  );
}
